[viewer]
Title = "Go语言博客"
Description = "Go语言博客"
Logo = "/resource/images/logo.png"
Navigation = ["首页", "/", "GO语言", "/golang", "归档", "/pigeonhole", "关于", "/about"]
Bilibili = "https://space.bilibili.com/27094875"
Zhihu = "https://www.zhihu.com/people/eric-li-87-52"
Avatar = "https://gimg2.baidu.com/image_search/src=http%3A%2F%2Finews.gtimg.com%2Fnewsapp_bt%2F0%2F13147603927%2F1000.jpg&refer=http%3A%2F%2Finews.gtimg.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=jpeg?sec=1647242040&t=c6108010ed46b4acebe18955acdd2d24"
UserName = "江城路Eric"
UserDesc = "菜鸟后端"
[system]
CdnURL = "https://static.mszlu.com/goblog/es6/md-assets"
QiniuAccessKey = "替换自己的"
QiniuSecretKey = "替换自己的"
Valine = true
ValineAppid = "fe1kxu1HyGvbSiXl3Re1AgFC-gzGzoHsz"
ValineAppkey = "Qn7T47qaxw06ldvla4xqrb5C"
ValineServerURL = "https://fe1kxu1h.lc-cn-n1-shared.com"